export const GET_ARTICULOS = "GET_ARTICULOS";
export const GET_ARTICULO = "GET_ARTICULO";
export const POST_ARTICULO = "POST_ARTICULO";
export const DELETE_ARTICULO = "DELETE_ARTICULO";
export const UPDATE_ARTICULO = "UPDATE_ARTICULO";
export const ARTICULO_ERROR = "ARTICULO_ERROR";
export const ARTICULO_START = "ARTICULO_START";
export const DEFAULT_ARTICLE = "DEFAULT_ARTICLE";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const POST_CATEGORY = "POST_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const CATEGORY_ERROR = "CATEGORY_ERROR";

export const GET_COMUNICADO = "GET_COMUNICADO";
export const GET_COMUNICADOS = "GET_COMUNICADOS";
export const POST_COMUNICADO = "POST_COMUNICADO";
export const DELETE_COMUNICADO = "DELETE_COMUNICADO";
export const UPDATE_COMUNICADO = "UPDATE_COMUNICADO";
export const COMUNICADO_ERROR = "COMUNICADO_ERROR";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOG_OUT = "LOG_OUT";
export const LOGIN_START = "LOGINT_START";
export const DEFAULT_SESSION = "DEFAULT_SESSION";

export const SEND_MAIL = "SEND_MAIL";
export const EMAIL_START = "EMAIL_START";
export const SET_DEFAULT_EMAIL = "SET_DEFAULT_EMAIL";
